language: node_js
node_js:
  - 'node'
before_install:
  - cd frontend
  - npm install yarn
after_success:
  - npm run build
  - npm install -g firebase-tools
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive
